# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List, Callable

from spacetimedb_sdk.spacetimedb_client import SpacetimeDBClient
from spacetimedb_sdk.spacetimedb_client import Identity


def create_npc(room_id: str, name: str, description: str):
	room_id = room_id
	name = name
	description = description
	SpacetimeDBClient.instance._reducer_call("create_npc", room_id, name, description)

def register_on_create_npc(callback: Callable[[Identity, str, str, str, str, str], None]):
	SpacetimeDBClient.instance._register_reducer("create_npc", callback)

def _decode_args(data):
	return [str(data[0]), str(data[1]), str(data[2])]
