# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List, Callable

from spacetimedb_sdk.spacetimedb_client import SpacetimeDBClient
from spacetimedb_sdk.spacetimedb_client import Identity


def create_world(world_id: str, world_name: str, world_description: str):
	world_id = world_id
	world_name = world_name
	world_description = world_description
	SpacetimeDBClient.instance._reducer_call("create_world", world_id, world_name, world_description)

def register_on_create_world(callback: Callable[[Identity, str, str, str, str, str], None]):
	SpacetimeDBClient.instance._register_reducer("create_world", callback)

def _decode_args(data):
	return [str(data[0]), str(data[1]), str(data[2])]
