# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List, Callable

from spacetimedb_sdk.spacetimedb_client import SpacetimeDBClient
from spacetimedb_sdk.spacetimedb_client import Identity


def create_player(name: str, description: str):
	name = name
	description = description
	SpacetimeDBClient.instance._reducer_call("create_player", name, description)

def register_on_create_player(callback: Callable[[Identity, str, str, str, str], None]):
	SpacetimeDBClient.instance._register_reducer("create_player", callback)

def _decode_args(data):
	return [str(data[0]), str(data[1])]
