# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List, Callable

from spacetimedb_sdk.spacetimedb_client import SpacetimeDBClient
from spacetimedb_sdk.spacetimedb_client import Identity


def go(source_spawnable_entity_id: int, exit_direction: str):
	source_spawnable_entity_id = source_spawnable_entity_id
	exit_direction = exit_direction
	SpacetimeDBClient.instance._reducer_call("go", source_spawnable_entity_id, exit_direction)

def register_on_go(callback: Callable[[Identity, str, str, int, str], None]):
	SpacetimeDBClient.instance._register_reducer("go", callback)

def _decode_args(data):
	return [int(data[0]), str(data[1])]
