# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from __future__ import annotations
from typing import List, Iterator, Callable

from spacetimedb_sdk.spacetimedb_client import SpacetimeDBClient, Identity
from spacetimedb_sdk.spacetimedb_client import ReducerEvent

class Npc:
	is_table_class = True

	primary_key = "spawnable_entity_id"

	@classmethod
	def register_row_update(cls, callback: Callable[[str,Npc,Npc,ReducerEvent], None]):
		SpacetimeDBClient.instance._register_row_update("Npc",callback)

	@classmethod
	def iter(cls) -> Iterator[Npc]:
		return SpacetimeDBClient.instance._get_table_cache("Npc").values()

	@classmethod
	def filter_by_spawnable_entity_id(cls, spawnable_entity_id) -> Npc:
		return next(iter([column_value for column_value in SpacetimeDBClient.instance._get_table_cache("Npc").values() if column_value.spawnable_entity_id == spawnable_entity_id]), None)

	def __init__(self, data: List[object]):
		self.data = {}
		self.data["spawnable_entity_id"] = int(data[0])

	def encode(self) -> List[object]:
		return [self.spawnable_entity_id]

	def __getattr__(self, name: str):
		return self.data.get(name)
