# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List, Callable

from spacetimedb_sdk.spacetimedb_client import SpacetimeDBClient
from spacetimedb_sdk.spacetimedb_client import Identity


reducer_name = "say"

def say(source_spawnable_entity_id: int, chat_text: str):
	source_spawnable_entity_id = source_spawnable_entity_id
	chat_text = chat_text
	SpacetimeDBClient.instance._reducer_call("say", source_spawnable_entity_id, chat_text)

def register_on_say(callback: Callable[[Identity, str, str, int, str], None]):
	SpacetimeDBClient.instance._register_reducer("say", callback)

def _decode_args(data):
	return [int(data[0]), str(data[1])]
