# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List, Callable

from spacetimedb_sdk.spacetimedb_client import SpacetimeDBClient
from spacetimedb_sdk.spacetimedb_client import Identity


reducer_name = "sign_out"

def sign_out(player_spawnable_entity_id: int):
	player_spawnable_entity_id = player_spawnable_entity_id
	SpacetimeDBClient.instance._reducer_call("sign_out", player_spawnable_entity_id)

def register_on_sign_out(callback: Callable[[Identity, str, str, int], None]):
	SpacetimeDBClient.instance._register_reducer("sign_out", callback)

def _decode_args(data):
	return [int(data[0])]
