// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue } from "@clockworklabs/spacetimedb-sdk";

export class CreateConnectionReducer
{
	public static call(fromRoomId: string, toRoomId: string, fromDirection: string, toDirection: string, fromExitDescription: string, toExitDescription: string)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.call("create_connection", [fromRoomId, toRoomId, fromDirection, toDirection, fromExitDescription, toExitDescription]);
		}
	}

	public static deserializeArgs(rawArgs: any[]): any[] {
		let fromRoomIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let fromRoomIdValue = AlgebraicValue.deserialize(fromRoomIdType, rawArgs[0])
		let fromRoomId = fromRoomIdValue.asString();
		let toRoomIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let toRoomIdValue = AlgebraicValue.deserialize(toRoomIdType, rawArgs[1])
		let toRoomId = toRoomIdValue.asString();
		let fromDirectionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let fromDirectionValue = AlgebraicValue.deserialize(fromDirectionType, rawArgs[2])
		let fromDirection = fromDirectionValue.asString();
		let toDirectionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let toDirectionValue = AlgebraicValue.deserialize(toDirectionType, rawArgs[3])
		let toDirection = toDirectionValue.asString();
		let fromExitDescriptionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let fromExitDescriptionValue = AlgebraicValue.deserialize(fromExitDescriptionType, rawArgs[4])
		let fromExitDescription = fromExitDescriptionValue.asString();
		let toExitDescriptionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let toExitDescriptionValue = AlgebraicValue.deserialize(toExitDescriptionType, rawArgs[5])
		let toExitDescription = toExitDescriptionValue.asString();
		return [fromRoomId, toRoomId, fromDirection, toDirection, fromExitDescription, toExitDescription];
	}

	public static on(callback: (status: string, identity: string, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:CreateConnection", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("CreateConnection", CreateConnectionReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("CreateConnection", CreateConnectionReducer);
}

export default CreateConnectionReducer
