// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue } from "@clockworklabs/spacetimedb-sdk";

export class CreateZoneReducer
{
	public static call(zoneId: string, worldId: string, zoneName: string, zoneDescription: string)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.call("create_zone", [zoneId, worldId, zoneName, zoneDescription]);
		}
	}

	public static deserializeArgs(rawArgs: any[]): any[] {
		let zoneIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let zoneIdValue = AlgebraicValue.deserialize(zoneIdType, rawArgs[0])
		let zoneId = zoneIdValue.asString();
		let worldIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let worldIdValue = AlgebraicValue.deserialize(worldIdType, rawArgs[1])
		let worldId = worldIdValue.asString();
		let zoneNameType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let zoneNameValue = AlgebraicValue.deserialize(zoneNameType, rawArgs[2])
		let zoneName = zoneNameValue.asString();
		let zoneDescriptionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let zoneDescriptionValue = AlgebraicValue.deserialize(zoneDescriptionType, rawArgs[3])
		let zoneDescription = zoneDescriptionValue.asString();
		return [zoneId, worldId, zoneName, zoneDescription];
	}

	public static on(callback: (status: string, identity: string, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:CreateZone", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("CreateZone", CreateZoneReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("CreateZone", CreateZoneReducer);
}

export default CreateZoneReducer
