// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue } from "@clockworklabs/spacetimedb-sdk";

export class CreateWorldReducer
{
	public static call(worldId: string, worldName: string, worldDescription: string)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.call("create_world", [worldId, worldName, worldDescription]);
		}
	}

	public static deserializeArgs(rawArgs: any[]): any[] {
		let worldIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let worldIdValue = AlgebraicValue.deserialize(worldIdType, rawArgs[0])
		let worldId = worldIdValue.asString();
		let worldNameType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let worldNameValue = AlgebraicValue.deserialize(worldNameType, rawArgs[1])
		let worldName = worldNameValue.asString();
		let worldDescriptionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let worldDescriptionValue = AlgebraicValue.deserialize(worldDescriptionType, rawArgs[2])
		let worldDescription = worldDescriptionValue.asString();
		return [worldId, worldName, worldDescription];
	}

	public static on(callback: (status: string, identity: string, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:CreateWorld", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("CreateWorld", CreateWorldReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("CreateWorld", CreateWorldReducer);
}

export default CreateWorldReducer
