// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue, ReducerArgsAdapter, SumTypeVariant, Serializer, Identity, ReducerEvent } from "@clockworklabs/spacetimedb-sdk";

export class CreateNpcReducer
{
	public static call(_roomId: string, _name: string, _description: string)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
		const serializer = __SPACETIMEDB__.spacetimeDBClient.getSerializer();
		let _roomIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		serializer.write(_roomIdType, _roomId);
		let _nameType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		serializer.write(_nameType, _name);
		let _descriptionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		serializer.write(_descriptionType, _description);
			__SPACETIMEDB__.spacetimeDBClient.call("create_npc", serializer);
		}
	}

	public static deserializeArgs(adapter: ReducerArgsAdapter): any[] {
		let roomIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let roomIdValue = AlgebraicValue.deserialize(roomIdType, adapter.next())
		let roomId = roomIdValue.asString();
		let nameType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let nameValue = AlgebraicValue.deserialize(nameType, adapter.next())
		let name = nameValue.asString();
		let descriptionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let descriptionValue = AlgebraicValue.deserialize(descriptionType, adapter.next())
		let description = descriptionValue.asString();
		return [roomId, name, description];
	}

	public static on(callback: (reducerEvent: ReducerEvent, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:CreateNpc", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("CreateNpc", CreateNpcReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("CreateNpc", CreateNpcReducer);
}

export default CreateNpcReducer
