// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, SumType, SumTypeVariant, IDatabaseTable, AlgebraicValue } from "@clockworklabs/spacetimedb-sdk";

export class Exit extends IDatabaseTable
{
	public static tableName = "Exit";
	public direction: string;
	public examine: string;
	public destinationRoomId: string;

	constructor(direction: string, examine: string, destinationRoomId: string) {
	super();
		this.direction = direction;
		this.examine = examine;
		this.destinationRoomId = destinationRoomId;
	}

	public static serialize(value: Exit): object {
		return [
		value.direction, value.examine, value.destinationRoomId
		];
	}

	public static getAlgebraicType(): AlgebraicType
	{
		return AlgebraicType.createProductType([
			new ProductTypeElement("direction", AlgebraicType.createPrimitiveType(BuiltinType.Type.String)),
			new ProductTypeElement("examine", AlgebraicType.createPrimitiveType(BuiltinType.Type.String)),
			new ProductTypeElement("destination_room_id", AlgebraicType.createPrimitiveType(BuiltinType.Type.String)),
		]);
	}

	public static fromValue(value: AlgebraicValue): Exit
	{
		let productValue = value.asProductValue();
		let __direction = productValue.elements[0].asString();
		let __examine = productValue.elements[1].asString();
		let __destination_room_id = productValue.elements[2].asString();
		return new this(__direction, __examine, __destination_room_id);
	}

}

export default Exit;

__SPACETIMEDB__.registerComponent("Exit", Exit);
