// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue, ReducerArgsAdapter, SumTypeVariant, Serializer, Identity, ReducerEvent } from "@clockworklabs/spacetimedb-sdk";

export class GoReducer
{
	public static call(_sourceSpawnableEntityId: number, _exitDirection: string)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
		const serializer = __SPACETIMEDB__.spacetimeDBClient.getSerializer();
		let _sourceSpawnableEntityIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U32);
		serializer.write(_sourceSpawnableEntityIdType, _sourceSpawnableEntityId);
		let _exitDirectionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		serializer.write(_exitDirectionType, _exitDirection);
			__SPACETIMEDB__.spacetimeDBClient.call("go", serializer);
		}
	}

	public static deserializeArgs(adapter: ReducerArgsAdapter): any[] {
		let sourceSpawnableEntityIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U32);
		let sourceSpawnableEntityIdValue = AlgebraicValue.deserialize(sourceSpawnableEntityIdType, adapter.next())
		let sourceSpawnableEntityId = sourceSpawnableEntityIdValue.asNumber();
		let exitDirectionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let exitDirectionValue = AlgebraicValue.deserialize(exitDirectionType, adapter.next())
		let exitDirection = exitDirectionValue.asString();
		return [sourceSpawnableEntityId, exitDirection];
	}

	public static on(callback: (reducerEvent: ReducerEvent, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:Go", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("Go", GoReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("Go", GoReducer);
}

export default GoReducer
