// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue } from "@clockworklabs/spacetimedb-sdk";

export class GoReducer
{
	public static call(sourceSpawnableEntityId: number, exitDirection: string)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.call("go", [sourceSpawnableEntityId, exitDirection]);
		}
	}

	public static deserializeArgs(rawArgs: any[]): any[] {
		let sourceSpawnableEntityIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U64);
		let sourceSpawnableEntityIdValue = AlgebraicValue.deserialize(sourceSpawnableEntityIdType, rawArgs[0])
		let sourceSpawnableEntityId = sourceSpawnableEntityIdValue.asNumber();
		let exitDirectionType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let exitDirectionValue = AlgebraicValue.deserialize(exitDirectionType, rawArgs[1])
		let exitDirection = exitDirectionValue.asString();
		return [sourceSpawnableEntityId, exitDirection];
	}

	public static on(callback: (status: string, identity: string, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:Go", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("Go", GoReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("Go", GoReducer);
}

export default GoReducer
