// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue } from "@clockworklabs/spacetimedb-sdk";

export class SayReducer
{
	public static call(sourceSpawnableEntityId: number, chatText: string)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.call("say", [sourceSpawnableEntityId, chatText]);
		}
	}

	public static deserializeArgs(rawArgs: any[]): any[] {
		let sourceSpawnableEntityIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U64);
		let sourceSpawnableEntityIdValue = AlgebraicValue.deserialize(sourceSpawnableEntityIdType, rawArgs[0])
		let sourceSpawnableEntityId = sourceSpawnableEntityIdValue.asNumber();
		let chatTextType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let chatTextValue = AlgebraicValue.deserialize(chatTextType, rawArgs[1])
		let chatText = chatTextValue.asString();
		return [sourceSpawnableEntityId, chatText];
	}

	public static on(callback: (status: string, identity: string, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:Say", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("Say", SayReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("Say", SayReducer);
}

export default SayReducer
